# Generated by Django 2.0.5 on 2018-05-04 00:25

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat', models.CharField(default='N/A', max_length=40)),
                ('date', models.CharField(default='N/A', max_length=40)),
                ('time', models.CharField(default='N/A', max_length=40)),
                ('session_type', models.CharField(default='N/A', max_length=40)),
                ('speed_input', models.CharField(default='N/A', max_length=40)),
                ('total_distance', models.CharField(default='N/A', max_length=6)),
                ('distance_from_start', jsonfield.fields.JSONField(default=dict, max_length=10)),
                ('total_time', models.CharField(default='N/A', max_length=15)),
                ('avg_stroke_rate', models.CharField(default='N/A', max_length=6)),
                ('avg_split', models.CharField(default='N/A', max_length=6)),
                ('avg_speed', models.CharField(default='N/A', max_length=6)),
                ('stroke_rate', jsonfield.fields.JSONField(default=dict, max_length=10)),
                ('elapsed_time', jsonfield.fields.JSONField(default=dict, max_length=10)),
                ('split', jsonfield.fields.JSONField(default=dict, max_length=10)),
                ('speed', jsonfield.fields.JSONField(default=dict, max_length=10)),
                ('distance_per_stroke', jsonfield.fields.JSONField(default=dict, max_length=10)),
                ('slug', models.SlugField(max_length=40, unique=True)),
            ],
        ),
    ]
